"""Increase password_hash length

Revision ID: 44fa587c057e
Revises: 
Create Date: 2025-08-21 18:55:01.292233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44fa587c057e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones')
    op.drop_table('forests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.create_unique_constraint(None, ['telephone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    op.create_table('forests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('forests_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('surface', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='forests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zone_type', postgresql.ENUM('polluted', 'water', 'exploitation', 'biodiversity', name='zone_type'), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('surface', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pollution_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('water_quality', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('next_cut_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('biodiversity_intensity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['forest_id'], ['forests.id'], name=op.f('zones_forest_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('zones_pkey'))
    )
    # ### end Alembic commands ###
